In [31]:
class Employee:
    emp_count = 0
    def __init__(self,name,family,salary,department):
        self.Name = name
        self.Family = family
        self.Salary = salary
        self.Department = department
        Employee.emp_count += 1
    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.Salary
        return sum / Employee.emp_count
    
class FulltimeEmployee(Employee):

    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

    def year_end_bonus(self):
        print("Year end bonus is provided for full time employees.")

def main():
    employees = []
    e1 = FulltimeEmployee("Bob", "william", 6000, "CS")
    e2 = FulltimeEmployee("Mary", "Thomas", 8529.486, "IT")
    e3 = FulltimeEmployee("Harry", "Potter", 1596, "Management")
    
    e1.year_end_bonus()
    employees.append(e1)
    employees.append(e2)
    employees.append(e3)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()

Year end bonus is provided for full time employees.
Average salary: 5375.162


Created a class named Employee and created a data member named emp_count to count the number of employees. Constuctor has been created to initialize parameters. average_salary funtion is created and employees list is passed as an argument to calculate average salary. Full_Time_Employee class has been created that extends the properties of Employee class. average_salary function is called by creating the object for Full_Time_Employee class.

In [32]:
# importing numpy
import numpy as np
a = np.random.uniform(1,20,20)
print(a)

array = a;
print("Array : " + str(array))
n = array.size

N = 4
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped = array.reshape((N, M))

# printing reshaped array
print("First Reshaped Array 4 x 5 : ")
print(reshaped)

a = reshaped
b = a
b[np.arange(len(a)), a.argmax(1)] = 0
print(b)

[ 9.63124347 15.3712248  10.06871979  8.76620816  3.82275108  7.57478634
 15.88551222 15.77609843 12.32798532  2.04064447  9.36746268 10.26188993
 15.10721864  9.1514908   8.06312829  4.80214331  5.19954715 17.57608127
 18.9058742   8.85953908]
Array : [ 9.63124347 15.3712248  10.06871979  8.76620816  3.82275108  7.57478634
 15.88551222 15.77609843 12.32798532  2.04064447  9.36746268 10.26188993
 15.10721864  9.1514908   8.06312829  4.80214331  5.19954715 17.57608127
 18.9058742   8.85953908]
First Reshaped Array 4 x 5 : 
[[ 9.63124347 15.3712248  10.06871979  8.76620816  3.82275108]
 [ 7.57478634 15.88551222 15.77609843 12.32798532  2.04064447]
 [ 9.36746268 10.26188993 15.10721864  9.1514908   8.06312829]
 [ 4.80214331  5.19954715 17.57608127 18.9058742   8.85953908]]
[[ 9.63124347  0.         10.06871979  8.76620816  3.82275108]
 [ 7.57478634  0.         15.77609843 12.32798532  2.04064447]
 [ 9.36746268 10.26188993  0.          9.1514908   8.06312829]
 [ 4.80214331  5.19954715 17.5

Imported numpy library and A vector has been created with random values of size 20 with range between 1 to 20. Array is reshaped to size of rows and columns of 4 and 5 using reshape method. Maximum element of each row of array is replaced with zero.